# -*- coding: utf-8 -*-
"""Assignment 1 Part 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkTM8LTMEvTyNVGIKboq0GlsKIHSXoZF
"""

import torch
import torch.nn as nn
import math
import time
from collections import Counter, defaultdict
from datasets import load_dataset
import re
import random

# ==============================================================================
# 0. HYPERPARAMETERS & CONFIGURATION
# ==============================================================================
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
EMBED_SIZE = 128
HIDDEN_SIZE = 256
BATCH_SIZE = 32
SEQ_LEN = 35
EPOCHS = 20
LEARNING_RATE = 0.001
MAX_TOKENS = 100000
# ==============================================================================
# 0.5 DATA LOADING (IMDB MOVIE REVIEWS - BALANCED)
# ==============================================================================
def load_imdb_data(max_tokens=MAX_TOKENS):
    print(f"Loading IMDB dataset (Limited to {max_tokens} tokens for speed)...")
    dataset = load_dataset("imdb")

    # Extract balanced text (Half negative, half positive)
    train_reviews = dataset['train']['text'][:250] + dataset['train']['text'][-250:]
    val_reviews = dataset['test']['text'][:50] + dataset['test']['text'][-50:]

    # Shuffle the reviews to mix positive and negative
    random.seed(42)
    random.shuffle(train_reviews)
    random.shuffle(val_reviews)

    def clean_text(text):
        text = text.lower()
        text = re.sub(r'<br\s*/>', ' ', text)
        return re.sub(r'[^a-z0-9\s]', '', text).split()

    train_words = []
    for review in train_reviews:
        train_words.extend(clean_text(review))
    train_words = train_words[:max_tokens]

    val_words = []
    for review in val_reviews:
        val_words.extend(clean_text(review))
    val_words = val_words[:max_tokens // 5]

    # Build Vocabulary
    counter = Counter(train_words)
    vocab = {word: i+2 for i, word in enumerate(counter.keys())}
    vocab['<unk>'] = 0
    vocab['<pad>'] = 1
    idx_to_word = {i: word for word, i in vocab.items()}

    # Encode for PyTorch models
    def encode_lm(text_list):
        tokens = [vocab.get(word, 0) for word in text_list]
        return torch.tensor(tokens, dtype=torch.long)

    train_data_lm = encode_lm(train_words)
    val_data_lm = encode_lm(val_words)

    def batchify(data, bsz):
        seq_len_actual = data.size(0) // bsz
        data = data[:seq_len_actual * bsz]
        return data.view(bsz, seq_len_actual).t().contiguous().to(DEVICE)

    train_data_lm = batchify(train_data_lm, BATCH_SIZE)
    val_data_lm = batchify(val_data_lm, BATCH_SIZE)

    return train_data_lm, val_data_lm, train_words, val_words, vocab, idx_to_word

def get_lm_batch(source, i, seq_len=SEQ_LEN):
    seq_len_actual = min(seq_len, len(source) - 1 - i)
    data = source[i:i+seq_len_actual]
    target = source[i+1:i+1+seq_len_actual].reshape(-1)
    return data, target

# ==============================================================================
# PART I: LANGUAGE MODELS ARCHITECTURES
# ==============================================================================

class NGramLM:
    """A simple N-Gram language model using Maximum Likelihood Estimation."""
    def __init__(self, n=3):
        self.n = n
        self.ngram_counts = defaultdict(int)
        self.context_counts = defaultdict(int)
        self.vocab = set()
        self.vocab_size = 0

    def train(self, tokenized_corpus):
        for i in range(len(tokenized_corpus) - self.n + 1):
            ngram = tuple(tokenized_corpus[i:i+self.n])
            context = tuple(tokenized_corpus[i:i+self.n-1])
            self.ngram_counts[ngram] += 1
            self.context_counts[context] += 1
            self.vocab.add(tokenized_corpus[i])
        self.vocab_size = len(self.vocab)

    def evaluate(self, tokenized_corpus):
        """Calculates Perplexity for the N-gram model."""
        log_prob_sum = 0
        for i in range(len(tokenized_corpus) - self.n + 1):
            ngram = tuple(tokenized_corpus[i:i+self.n])
            context = tuple(tokenized_corpus[i:i+self.n-1])
            count = self.ngram_counts.get(ngram, 0)
            ctx_count = self.context_counts.get(context, 0)
            # Add-1 Smoothing
            prob = (count + 1) / (ctx_count + self.vocab_size)
            log_prob_sum += math.log(prob)
        avg_log_prob = log_prob_sum / (len(tokenized_corpus) - self.n + 1)
        return math.exp(-avg_log_prob)

    def generate(self, start_context, max_len=20):
        current_context = tuple(start_context[-(self.n-1):])
        generated = list(start_context)
        for _ in range(max_len):
            best_word, best_prob = None, -1
            for word in self.vocab:
                ngram = current_context + (word,)
                count = self.ngram_counts.get(ngram, 0)
                ctx_count = self.context_counts.get(current_context, 0)
                prob = (count + 1) / (ctx_count + self.vocab_size)
                if prob > best_prob:
                    best_prob, best_word = prob, word
            generated.append(best_word)
            current_context = tuple(generated[-(self.n-1):])
        return " ".join(generated)

class NeuralLMBase(nn.Module):
    """Base neural module"""
    def __init__(self, vocab_size, embed_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)

class RNNModel(NeuralLMBase):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__(vocab_size, embed_size)
        self.rnn = nn.RNN(embed_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden=None):
        emb = self.embedding(x)
        out, hidden = self.rnn(emb, hidden)
        logits = self.fc(out)
        return logits, hidden

class LSTMModel(NeuralLMBase):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__(vocab_size, embed_size)
        self.lstm = nn.LSTM(embed_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden=None):
        emb = self.embedding(x)
        out, hidden = self.lstm(emb, hidden)
        logits = self.fc(out)
        return logits, hidden

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        x = x + self.pe[:, :x.size(1)]
        return x

class TransformerLM(NeuralLMBase):
    def __init__(self, vocab_size, embed_size, num_heads=4, hidden_size=256, num_layers=2):
        super().__init__(vocab_size, embed_size)
        self.pos_encoder = PositionalEncoding(embed_size)
        encoder_layers = nn.TransformerEncoderLayer(embed_size, num_heads, hidden_size, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layers, num_layers)
        self.fc = nn.Linear(embed_size, vocab_size)
        self.embed_size = embed_size

    def generate_square_subsequent_mask(self, sz):
        mask = (torch.triu(torch.ones(sz, sz)) == 1).transpose(0, 1)
        mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
        return mask.to(DEVICE)

    def forward(self, x, hidden=None):
        src_mask = self.generate_square_subsequent_mask(x.size(1))
        emb = self.embedding(x) * math.sqrt(self.embed_size)
        emb = self.pos_encoder(emb)
        out = self.transformer_encoder(emb, src_mask)
        logits = self.fc(out)
        return logits, None

# ==============================================================================
# TRAINING & EVALUATION FUNCTIONS
# ==============================================================================
def train_lm(model, data_source, criterion, optimizer):
    model.train()
    total_loss = 0.
    start_time = time.time()
    for i in range(0, data_source.size(0) - 1, SEQ_LEN):
        inputs, targets = get_lm_batch(data_source, i)
        optimizer.zero_grad()
        output, _ = model(inputs)
        loss = criterion(output.view(-1, output.size(-1)), targets)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        optimizer.step()
        total_loss += loss.item()
    batches = max(1, (data_source.size(0) - 1) // SEQ_LEN)
    return total_loss / batches, time.time() - start_time

def evaluate_lm(model, data_source, criterion):
    model.eval()
    total_loss = 0.
    start_time = time.time()
    with torch.no_grad():
        for i in range(0, data_source.size(0) - 1, SEQ_LEN):
            inputs, targets = get_lm_batch(data_source, i)
            output, _ = model(inputs)
            loss = criterion(output.view(-1, output.size(-1)), targets)
            total_loss += loss.item()
    batches = max(1, (data_source.size(0) - 1) // SEQ_LEN)
    inference_time_per_batch = (time.time() - start_time) / batches
    return total_loss / batches, inference_time_per_batch

def generate_neural_text(model, vocab, i2w, start_sequence, max_len=15):
    """Generates a sequence of text to test the model's qualitative performance."""
    model.eval()
    words = start_sequence.lower().split()
    input_ids = torch.tensor([[vocab.get(w, 0) for w in words]]).to(DEVICE)
    with torch.no_grad():
        for _ in range(max_len):
            output, _ = model(input_ids)
            last_word_logits = output[0, -1, :]
            predicted_id = torch.argmax(last_word_logits).item()
            predicted_word = i2w.get(predicted_id, '<unk>')
            words.append(predicted_word)
            input_ids = torch.cat([input_ids, torch.tensor([[predicted_id]]).to(DEVICE)], dim=1)
    return " ".join(words)

# ==============================================================================
# MAIN EXECUTION BLOCK - ONLY PART I
# ==============================================================================
if __name__ == "__main__":
    print("🚀 Starting Part I: Training all 4 Language Models...\n")

    # 1. Load Data
    train_lm_data, val_lm_data, train_words, val_words, vocab, idx_to_word = load_imdb_data()
    vocab_size = len(vocab)
    print(f"✅ Data loaded! Vocab Size: {vocab_size}")

    criterion = nn.CrossEntropyLoss()
    prompt = "this movie was"

    # Dictionaries to store results for the final summary table
    results = {}
    generated_texts = {}

    # ---------------------------------------------------------
    # 1. N-Gram Model
    # ---------------------------------------------------------
    print("\n[1/4] Training N-Gram Model (n=3)...")
    start_t = time.time()
    ngram_model = NGramLM(n=3)
    ngram_model.train(train_words)
    train_time_ngram = time.time() - start_t

    start_t = time.time()
    ngram_ppl = ngram_model.evaluate(val_words)
    inf_time_ngram = (time.time() - start_t) / (len(val_words)/BATCH_SIZE) # Approximate per batch

    results['N-gram'] = {'Train Time': f"{train_time_ngram:.2f}s (Total)", 'Inf Time': f"{inf_time_ngram:.4f}s", 'PPL': ngram_ppl}
    generated_texts['N-gram'] = ngram_model.generate(prompt.split(), max_len=15)

    # ---------------------------------------------------------
    # Function to train Neural Models
    # ---------------------------------------------------------
    def run_neural_model(name, model_class):
        print(f"\n[{name}] Initializing...")
        model = model_class(vocab_size, EMBED_SIZE, HIDDEN_SIZE).to(DEVICE) if name != 'Transformer' else model_class(vocab_size, EMBED_SIZE).to(DEVICE)
        optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

        total_train_time = 0
        for epoch in range(1, EPOCHS + 1):
            loss, t_time = train_lm(model, train_lm_data, criterion, optimizer)
            total_train_time += t_time
            print(f"  Epoch {epoch}/{EPOCHS} | Loss: {loss:.6f} | Time: {t_time:.6f}s")

        val_loss, inf_time = evaluate_lm(model, val_lm_data, criterion)
        val_ppl = math.exp(val_loss)

        avg_train_time = total_train_time / EPOCHS
        results[name] = {'Train Time': f"{avg_train_time:.6f}s /epoch", 'Inf Time': f"{inf_time:.6f}s", 'PPL': val_ppl}
        generated_texts[name] = generate_neural_text(model, vocab, idx_to_word, prompt, max_len=15)

    # ---------------------------------------------------------
    # 2. RNN Model
    # ---------------------------------------------------------
    run_neural_model('RNN', RNNModel)

    # ---------------------------------------------------------
    # 3. LSTM Model
    # ---------------------------------------------------------
    run_neural_model('LSTM', LSTMModel)

    # ---------------------------------------------------------
    # 4. Transformer Model
    # ---------------------------------------------------------
    run_neural_model('Transformer', TransformerLM)

    # ---------------------------------------------------------
    # PRINTING THE FINAL RESULTS FOR THE REPORT
    # ---------------------------------------------------------
    print("\n" + "="*60)
    print(" 🎉 ALL MODELS TRAINED! ")
    print("="*60)

    print("\n### 2.2 Quantitative Results")
    print("| Model | Training Time (per epoch) | Inference Time (per batch) | Validation Perplexity |")
    print("| :--- | :--- | :--- | :--- |")
    for model_name, metrics in results.items():
        print(f"| **{model_name}** | {metrics['Train Time']} | {metrics['Inf Time']} | {metrics['PPL']:.6f} |")

    print("\n### 2.3 Qualitative Behavior")
    print(f"* **Prompt:** \"{prompt}\"")
    for model_name, text in generated_texts.items():
        print(f"* **{model_name}:** {text}")
    print("="*60)