# -*- coding: utf-8 -*-
"""Assignment 1 Part III

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJYt-AZUhBjDg74Gsy-6a11-CHt0kL_K
"""

import torch
import torch.nn as nn
import time
from collections import Counter
from datasets import load_dataset
import re
import random

# ==============================================================================
# 0. HYPERPARAMETERS
# ==============================================================================
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
EMBED_SIZE = 128
HIDDEN_SIZE = 256
BATCH_SIZE = 64      # Increased batch size for faster GPU processing
EPOCHS_LM = 20       # Train Language Model to get good representations
EPOCHS_CLF = 10      # Train Classifier
LEARNING_RATE = 0.001

# Increased data scale to achieve ~80% real accuracy
NUM_TRAIN_REVIEWS_PER_CLASS = 5000 # Total 10000 training reviews
NUM_VAL_REVIEWS_PER_CLASS = 500    # Total 1000 validation reviews
MAX_SEQ_LEN = 100    # Let the classifier read the first 100 words of each review

# ==============================================================================
# 1. DATA LOADING (IMDB)
# ==============================================================================
def load_imdb_classification_data():
    print("Loading IMDB dataset for Classification...")
    dataset = load_dataset("imdb")

    # Extract balanced text and labels (0 = Negative, 1 = Positive)
    train_reviews = dataset['train']['text'][:NUM_TRAIN_REVIEWS_PER_CLASS] + dataset['train']['text'][-NUM_TRAIN_REVIEWS_PER_CLASS:]
    train_labels = dataset['train']['label'][:NUM_TRAIN_REVIEWS_PER_CLASS] + dataset['train']['label'][-NUM_TRAIN_REVIEWS_PER_CLASS:]

    val_reviews = dataset['test']['text'][:NUM_VAL_REVIEWS_PER_CLASS] + dataset['test']['text'][-NUM_VAL_REVIEWS_PER_CLASS:]
    val_labels = dataset['test']['label'][:NUM_VAL_REVIEWS_PER_CLASS] + dataset['test']['label'][-NUM_VAL_REVIEWS_PER_CLASS:]

    # Shuffle
    train_paired = list(zip(train_reviews, train_labels))
    random.seed(42)
    random.shuffle(train_paired)
    train_reviews, train_labels = zip(*train_paired)

    val_paired = list(zip(val_reviews, val_labels))
    random.shuffle(val_paired)
    val_reviews, val_labels = zip(*val_paired)

    def clean_text(text):
        text = text.lower()
        text = re.sub(r'<br\s*/>', ' ', text)
        return re.sub(r'[^a-z0-9\s]', '', text).split()

    # Build Vocab from training data
    print("Building vocabulary...")
    all_train_words = []
    for r in train_reviews:
        all_train_words.extend(clean_text(r))

    counter = Counter(all_train_words)

    # FIX 1: Filter words first, THEN enumerate to ensure strictly contiguous IDs without gaps!
    valid_words = [word for word, count in counter.items() if count > 1]
    vocab = {word: i+2 for i, word in enumerate(valid_words)}
    vocab['<unk>'] = 0
    vocab['<pad>'] = 1

    # ---------------------------------------------------------
    # Format 1: For Language Modeling (Continuous text stream)
    # ---------------------------------------------------------
    train_data_lm = torch.tensor([vocab.get(w, 0) for w in all_train_words], dtype=torch.long)
    seq_len_actual = train_data_lm.size(0) // BATCH_SIZE
    train_data_lm = train_data_lm[:seq_len_actual * BATCH_SIZE].view(BATCH_SIZE, seq_len_actual).t().contiguous().to(DEVICE)

    # ---------------------------------------------------------
    # Format 2: For Classification (Batched Sequences)
    # ---------------------------------------------------------
    def encode_clf(reviews, labels):
        x, y = [], []
        for review, label in zip(reviews, labels):
            tokens = [vocab.get(w, 0) for w in clean_text(review)[:MAX_SEQ_LEN]]
            if len(tokens) < MAX_SEQ_LEN:
                tokens += [vocab['<pad>']] * (MAX_SEQ_LEN - len(tokens))
            x.append(tokens)
            y.append(label)
        return torch.tensor(x, dtype=torch.long), torch.tensor(y, dtype=torch.long)

    print("Encoding sequences for classification...")
    train_x, train_y = encode_clf(train_reviews, train_labels)
    val_x, val_y = encode_clf(val_reviews, val_labels)

    return train_data_lm, (train_x, train_y), (val_x, val_y), vocab

# ==============================================================================
# 2. LANGUAGE MODEL (To extract embeddings)
# ==============================================================================
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        # FIX 2: Removed batch_first=True. The LM data is structured as [seq_len, batch_size]
        self.lstm = nn.LSTM(embed_size, hidden_size)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        emb = self.embedding(x)
        out, _ = self.lstm(emb)
        return self.fc(out)

# ==============================================================================
# 3. DOWNSTREAM CLASSIFIER
# ==============================================================================
class SentimentClassifier(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size, pretrained_weights=None):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)

        if pretrained_weights is not None:
            self.embedding.weight.data.copy_(pretrained_weights)

        # We allow the embeddings to be fine-tuned along with the LSTM
        # batch_first=True is CORRECT here because Downstream data is [batch_size, seq_len]
        self.lstm = nn.LSTM(embed_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, 2) # 2 Classes: Pos/Neg

    def forward(self, x):
        emb = self.embedding(x)
        out, (hidden, _) = self.lstm(emb)
        return self.fc(hidden[-1]) # Use last hidden state for classification

# ==============================================================================
# 4. MAIN EXECUTION
# ==============================================================================
if __name__ == "__main__":
    print("🚀 Starting Part III: Downstream Task (Sentiment Analysis)\n")

    train_data_lm, clf_train, clf_val, vocab = load_imdb_classification_data()
    vocab_size = len(vocab)
    print(f"✅ Data loaded! Vocab Size: {vocab_size}")

    # ---------------------------------------------------------
    # STEP A: Train LM to get representations
    # ---------------------------------------------------------
    print(f"\n[Step A] Pre-training Language Model on {NUM_TRAIN_REVIEWS_PER_CLASS*2} reviews...")
    lm_model = LSTMModel(vocab_size, EMBED_SIZE, HIDDEN_SIZE).to(DEVICE)
    optimizer_lm = torch.optim.Adam(lm_model.parameters(), lr=LEARNING_RATE)
    criterion_lm = nn.CrossEntropyLoss()

    lm_model.train()
    for epoch in range(1, EPOCHS_LM + 1):
        total_loss = 0
        start_t = time.time()
        for i in range(0, train_data_lm.size(0) - 1, 35):
            seq_len = min(35, len(train_data_lm) - 1 - i)
            inputs = train_data_lm[i:i+seq_len]
            targets = train_data_lm[i+1:i+1+seq_len].reshape(-1)

            optimizer_lm.zero_grad()
            output = lm_model(inputs)
            loss = criterion_lm(output.view(-1, output.size(-1)), targets)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(lm_model.parameters(), 5.0)
            optimizer_lm.step()
            total_loss += loss.item()

        if epoch % 5 == 0 or epoch == 1:
            epoch_time = time.time() - start_t
            # Safeguard to prevent division by zero in logging
            num_batches = max(1, train_data_lm.size(0) // 35)
            print(f"  LM Epoch {epoch}/{EPOCHS_LM} | Loss: {total_loss/num_batches:.2f} | Time: {epoch_time:.1f}s")

    # EXTRACT LEARNED EMBEDDINGS
    learned_weights = lm_model.embedding.weight.data.clone()
    print("  ✅ Extracted learned embeddings from Language Model!")

    # ---------------------------------------------------------
    # STEP B: Train Downstream Classifiers
    # ---------------------------------------------------------
    train_x, train_y = clf_train
    val_x, val_y = clf_val
    criterion_clf = nn.CrossEntropyLoss()

    def train_classifier(name, pretrained_weights=None):
        print(f"\n[Step B] Training Classifier: {name}")
        model = SentimentClassifier(vocab_size, EMBED_SIZE, HIDDEN_SIZE, pretrained_weights).to(DEVICE)
        optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

        best_acc = 0.0
        final_acc = 0.0

        for epoch in range(1, EPOCHS_CLF + 1):
            model.train()
            for i in range(0, len(train_x), BATCH_SIZE):
                inputs = train_x[i:i+BATCH_SIZE].to(DEVICE)
                targets = train_y[i:i+BATCH_SIZE].to(DEVICE)
                optimizer.zero_grad()
                loss = criterion_clf(model(inputs), targets)
                loss.backward()
                optimizer.step()

            # Eval
            model.eval()
            correct = 0
            with torch.no_grad():
                for i in range(0, len(val_x), BATCH_SIZE):
                    inputs = val_x[i:i+BATCH_SIZE].to(DEVICE)
                    targets = val_y[i:i+BATCH_SIZE].to(DEVICE)
                    outputs = model(inputs)
                    predictions = torch.argmax(outputs, dim=1)
                    correct += (predictions == targets).sum().item()
            acc = (correct / len(val_x)) * 100.0
            best_acc = max(best_acc, acc)
            final_acc = acc
            print(f"  Epoch {epoch}/{EPOCHS_CLF} | Val Accuracy: {acc:.2f}%")

        return best_acc, final_acc

    # 1. Baseline: Learn from scratch
    best_scratch, final_scratch = train_classifier("Baseline (Random Embeddings learned from scratch)")

    # 2. Proposed: Transferred LM Embeddings
    best_transfer, final_transfer = train_classifier("Proposed (Transferred from Language Model)", pretrained_weights=learned_weights)

    print("\n" + "="*60)
    print(" 🎉 PART III COMPLETE! ")
    print("="*60)
    print("| Initialization Strategy | Peak Validation Accuracy |")
    print("| :--- | :--- |")
    print(f"| **Baseline (Learn from scratch)** | {best_scratch:.2f}% |")
    print(f"| **Transferred LM Embeddings** | {best_transfer:.2f}% |")
    print("="*60)