# -*- coding: utf-8 -*-
"""Assignment 1 Part II

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVO35RmIWvxmM8nztyaCZ3lWvNLo7fI9
"""

import torch
import torch.nn as nn
import math
import time
from collections import Counter
from datasets import load_dataset
import re
import random
import numpy as np

# ==============================================================================
# 0. HYPERPARAMETERS
# ==============================================================================
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
EMBED_SIZE = 50      # Set to 50 to match public GloVe-50d for fair comparison
HIDDEN_SIZE = 256
BATCH_SIZE = 32
SEQ_LEN = 35
EPOCHS = 20
LEARNING_RATE = 0.001
MAX_TOKENS = 100000

# ==============================================================================
# 1. DATA LOADING (IMDB)
# ==============================================================================
def load_imdb_data(max_tokens=MAX_TOKENS):
    print("Loading IMDB dataset...")
    dataset = load_dataset("imdb")

    train_reviews = dataset['train']['text'][:250] + dataset['train']['text'][-250:]
    val_reviews = dataset['test']['text'][:50] + dataset['test']['text'][-50:]
    random.seed(42)
    random.shuffle(train_reviews)
    random.shuffle(val_reviews)

    def clean_text(text):
        text = text.lower()
        text = re.sub(r'<br\s*/>', ' ', text)
        return re.sub(r'[^a-z0-9\s]', '', text).split()

    train_words = []
    for review in train_reviews: train_words.extend(clean_text(review))
    train_words = train_words[:max_tokens]

    val_words = []
    for review in val_reviews: val_words.extend(clean_text(review))
    val_words = val_words[:max_tokens // 5]

    counter = Counter(train_words)
    vocab = {word: i+2 for i, word in enumerate(counter.keys())}
    vocab['<unk>'] = 0
    vocab['<pad>'] = 1
    idx_to_word = {i: word for word, i in vocab.items()}

    def encode_lm(text_list):
        return torch.tensor([vocab.get(word, 0) for word in text_list], dtype=torch.long)

    train_data_lm = encode_lm(train_words)
    val_data_lm = encode_lm(val_words)

    def batchify(data, bsz):
        seq_len_actual = data.size(0) // bsz
        data = data[:seq_len_actual * bsz]
        return data.view(bsz, seq_len_actual).t().contiguous().to(DEVICE)

    return batchify(train_data_lm, BATCH_SIZE), batchify(val_data_lm, BATCH_SIZE), train_words, vocab, idx_to_word

def get_lm_batch(source, i):
    seq_len_actual = min(SEQ_LEN, len(source) - 1 - i)
    data = source[i:i+seq_len_actual]
    target = source[i+1:i+1+seq_len_actual].reshape(-1)
    return data, target

# ==============================================================================
# 2. CUSTOM WORD2VEC (CBOW) TRAINING
# ==============================================================================
class CBOW(nn.Module):
    def __init__(self, vocab_size, embed_size):
        super().__init__()
        self.embeddings = nn.Embedding(vocab_size, embed_size)
        self.linear = nn.Linear(embed_size, vocab_size)

    def forward(self, inputs):
        embeds = self.embeddings(inputs).mean(dim=1)
        return self.linear(embeds)

def train_custom_word2vec(train_words, vocab, embed_size=EMBED_SIZE):
    print("\n[Prep] Training Custom Word2Vec (CBOW) on IMDB subset...")
    vocab_size = len(vocab)
    model = CBOW(vocab_size, embed_size).to(DEVICE)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

    # Prepare CBOW data (Window size = 2)
    encoded = [vocab.get(w, 0) for w in train_words]
    contexts, targets = [], []
    for i in range(2, len(encoded) - 2):
        contexts.append([encoded[i-2], encoded[i-1], encoded[i+1], encoded[i+2]])
        targets.append(encoded[i])

    contexts = torch.tensor(contexts, dtype=torch.long).to(DEVICE)
    targets = torch.tensor(targets, dtype=torch.long).to(DEVICE)
    dataset = torch.utils.data.TensorDataset(contexts, targets)
    loader = torch.utils.data.DataLoader(dataset, batch_size=256, shuffle=True)

    model.train()
    for epoch in range(2): # 2 epochs is enough for a rough semantic space
        total_loss = 0
        for ctx, tgt in loader:
            optimizer.zero_grad()
            loss = criterion(model(ctx), tgt)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"  Word2Vec Epoch {epoch+1}/2 | Loss: {total_loss/len(loader):.4f}")

    return model.embeddings.weight.data.clone()

# ==============================================================================
# 3. PUBLIC GLOVE LOADER (OR SIMULATION)
# ==============================================================================
def get_public_embeddings(vocab, embed_size=EMBED_SIZE):
    print("\n[Prep] Fetching Public Embeddings (GloVe)...")
    vocab_size = len(vocab)
    weights = torch.randn(vocab_size, embed_size) # Fallback random init

    try:
        import gensim.downloader as api
        print("  Downloading/Loading glove-wiki-gigaword-50 via Gensim...")
        glove = api.load("glove-wiki-gigaword-50")
        found = 0
        for word, idx in vocab.items():
            if word in glove:
                weights[idx] = torch.tensor(glove[word])
                found += 1
        print(f"  Matched {found}/{vocab_size} words from public GloVe!")
    except Exception as e:
        print(f"  Could not load real GloVe ({e}). Simulating public embeddings...")

    return weights.to(DEVICE)

# ==============================================================================
# 4. LSTM LANGUAGE MODEL & PIPELINE
# ==============================================================================
class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size, pretrained_weights=None, freeze=False):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)

        if pretrained_weights is not None:
            self.embedding.weight.data.copy_(pretrained_weights)
        if freeze:
            self.embedding.weight.requires_grad = False

        self.lstm = nn.LSTM(embed_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, hidden=None):
        emb = self.embedding(x)
        out, hidden = self.lstm(emb, hidden)
        return self.fc(out), hidden

def run_lm_training(model_name, model, train_data, val_data, criterion):
    print(f"\n--- Training: {model_name} ---")
    # Only optimize unfrozen parameters!
    optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=LEARNING_RATE)

    history = []
    for epoch in range(1, EPOCHS + 1):
        model.train()
        total_loss = 0.
        start_time = time.time()
        for i in range(0, train_data.size(0) - 1, SEQ_LEN):
            inputs, targets = get_lm_batch(train_data, i)
            optimizer.zero_grad()
            output, _ = model(inputs)
            loss = criterion(output.view(-1, output.size(-1)), targets)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            optimizer.step()
            total_loss += loss.item()

        train_loss = total_loss / max(1, (train_data.size(0) - 1) // SEQ_LEN)

        # Validation
        model.eval()
        val_loss = 0.
        with torch.no_grad():
            for i in range(0, val_data.size(0) - 1, SEQ_LEN):
                inputs, targets = get_lm_batch(val_data, i)
                output, _ = model(inputs)
                loss = criterion(output.view(-1, output.size(-1)), targets)
                val_loss += loss.item()
        val_loss = val_loss / max(1, (val_data.size(0) - 1) // SEQ_LEN)

        val_ppl = math.exp(val_loss)
        train_time = time.time() - start_time
        history.append(val_ppl)
        print(f"  Epoch {epoch}/{EPOCHS} | Train Loss: {train_loss:.6f} | Val PPL: {val_ppl:.6f} | Time: {train_time:.6f}s")

    return history[-1] # Return final Perplexity

# ==============================================================================
# 5. MAIN EXECUTION
# ==============================================================================
if __name__ == "__main__":
    print("🚀 Starting Part II: Embedding Variants and Ablation\n")

    train_lm_data, val_lm_data, train_words, vocab, idx_to_word = load_imdb_data()
    vocab_size = len(vocab)
    print(f"✅ Data loaded! Vocab Size: {vocab_size}")

    # Prepare the custom and public weights
    custom_weights = train_custom_word2vec(train_words, vocab)
    public_weights = get_public_embeddings(vocab)

    criterion = nn.CrossEntropyLoss()
    results = {}

    # --- Setting 1: Trainable from scratch ---
    model_scratch = LSTMModel(vocab_size, EMBED_SIZE, HIDDEN_SIZE).to(DEVICE)
    results['Scratch (Unfrozen)'] = run_lm_training("Setting 1: Scratch (Unfrozen)", model_scratch, train_lm_data, val_lm_data, criterion)

    # --- Setting 2: Fixed Custom Word2Vec ---
    model_custom = LSTMModel(vocab_size, EMBED_SIZE, HIDDEN_SIZE, pretrained_weights=custom_weights, freeze=True).to(DEVICE)
    results['Custom W2V (Fixed)'] = run_lm_training("Setting 2: Custom Word2Vec (Fixed)", model_custom, train_lm_data, val_lm_data, criterion)

    # --- Setting 3: Fixed Public Pretrained ---
    model_public = LSTMModel(vocab_size, EMBED_SIZE, HIDDEN_SIZE, pretrained_weights=public_weights, freeze=True).to(DEVICE)
    results['Public GloVe (Fixed)'] = run_lm_training("Setting 3: Public GloVe (Fixed)", model_public, train_lm_data, val_lm_data, criterion)

    print("\n" + "="*50)
    print(" 🎉 PART II COMPLETE! ")
    print("="*50)
    print("| Embedding Type | Validation PPL (Final) | Stability & Speed |")
    print("| :--- | :--- | :--- |")
    for name, ppl in results.items():
        print(f"| **{name}** | {ppl:.6f} | [See Analysis] |")
    print("="*50)